config/routes.rb
# Need to not fail when uri contains curly braces
# This overrides the DEFAULT_PARSER with the UNRESERVED key, including '{' and '}'
# DEFAULT_PARSER is used everywhere, so its better to override it once
module URI
  remove_const :DEFAULT_PARSER
  unreserved = REGEXP::PATTERN::UNRESERVED
  DEFAULT_PARSER = Parser.new(:UNRESERVED => unreserved + "\{\}\^")
end

GenieacsGui::Application.routes.draw do
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'log_in' => 'sessions#create'

  root 'home#index'
  get 'devices' => 'devices#index'
  get 'devices/:id' => 'devices#show'
  post 'devices/:id' => 'devices#update'
  delete 'devices/:id' => 'devices#destroy'

  get 'faults' => 'faults#index'
  post 'faults/:id/retry' => 'faults#retry'
  delete 'faults/:id' => 'faults#destroy'

  get 'presets' => 'presets#index'
  get 'presets/new' => 'presets#new'
  get 'presets/:id/edit' => 'presets#edit'
  post 'presets' => 'presets#update'
  delete 'presets/:id' => 'presets#destroy'

  get 'objects' => 'objects#index'
  get 'objects/new' => 'objects#new'
  get 'objects/:id/edit' => 'objects#edit'
  post 'objects' => 'objects#update'
  delete 'objects/:id' => 'objects#destroy'

  get 'files' => 'files#index'
  get 'files/new' => 'files#new'
  post 'files' => 'files#upload'
  delete 'files/:id' => 'files#destroy', :constraints => { :id => /.*/ }

  get 'ping/:ip' => 'ping#index', :constraints => { :ip => /[0-9\.]+/ }
end

app/views/layouts/_menu.html.erb
<ul class="menu">
  <% if can?(:read, 'home') %>
  <li class="<%= params[:controller] == 'home' ? 'active' : ''%>" >
    <%= link_to 'Home', root_path %>
  </li>
  <% end %>
  <% if can?(:read, 'devices') %>
  <li class="<%= params[:controller] == 'devices' ? 'active' : ''%>" >
    <%= link_to 'Devices', devices_path %>
  </li>
  <% end %>
  <% if can?(:read, 'tasks') %>
  <li class="<%= params[:controller] == 'faults' ? 'active' : ''%>" >
    <%= link_to 'Faults', faults_path %>
  </li>
  <% end %>
  <% if can?(:read, 'presets') %>
  <li class="<%= params[:controller] == 'presets' ? 'active' : ''%>" >
    <%= link_to 'Presets', presets_path %>
  </li>
  <% end %>
  <% if can?(:read, 'objects') %>
  <li class="<%= params[:controller] == 'objects' ? 'active' : ''%>" >
    <%= link_to 'Objects', objects_path %>
  </li>
  <% end %>
  <% if can?(:read, 'files') %>
  <li class="<%= params[:controller] == 'files' ? 'active' : ''%>" >
    <%= link_to 'Files', files_path %>
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) +' - ' : yield('') %>GenieACS</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
</head>
<body>
<div id="header">
  <div id="user_menu" style="float: right; margin: 5px;">
    <% if logged_in? %>
      <%= current_user %> | <%= link_to 'Log out', log_out_path %>
    <% else %>
      <%= link_to 'Log in', log_in_path %>
    <% end %>
  </div>
  <%= image_tag('logo.png', class: 'logo') %>
  <%= render 'layouts/menu' %>
</div>

<div id="content">
<%- flash.each do |k, v| %>
  <div class="flash <%= k %>"><%= v %></div>
<% end %>

<%= yield %>
</div>
</body>
</html>